<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="mobile_base.xacro" />
    <xacro:include filename="common_properties.xacro" />
    <xacro:include filename="gazebo_control.xacro" />

    <!-- <xacro:include filename="arm.xacro" /> -->
    <!-- <xacro:include filename="arm_gazebo.xacro" /> -->

    <!-- <xacro:include filename="camera.xacro" /> -->

    <!-- <joint name="mobile_base_arm_joint" type="fixed">
        <parent link="base_link" />
        <child link="arm_base_link" />
        <origin xyz="${base_length/3} 0 ${base_height}" rpy="0 0 0" />
    </joint> -->

    

</robot>